services:
  # Servicio de Node-RED
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
    networks:
      - app-network
    restart: unless-stopped

  # Servicio de usuarios
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./user-service:/usr/src/app
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev
    environment:
      - NODE_ENV=development

  # Servicio de máquinas
  machine-service:
    build:
      context: ./machine-service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./machine-service:/app  # AQUI ESTÁ EL CAMBIO. Mapeamos la carpeta de tu equipo con la app del contenedor.
    networks:
      - app-network
    command: npm run dev
    restart: unless-stopped

networks:
  app-network:
    driver: bridge