services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  machine-service:
    build:
      context: ./machine-service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./machine-service:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev
networks:
  app-network:
    driver: bridge