services:
  # Nodered
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
    networks:
      - app-network
    restart: unless-stopped

  # Servicio de base de datos
  db:
    container_name: postgres-db
    build:
      context: ./postgresql
      dockerfile: dockerfile
    env_file:
      - ./postgresql/.env
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Servicio de API rest de sesiones de usuarios
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev
    environment:
      - NODE_ENV=development

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
