; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	MFRC522
	MPU6050
	PubSubClient
	CoAP simple library
	SPI
	Wire
	bblanchon/ArduinoJson@^7.2.1
monitor_speed = 115200
upload_speed = 1000000

[env:rfid]
build_src_filter = 
	-<**/*.cpp>
	+<**/rfid.cpp>
lib_deps =

[env:pir-led]
build_src_filter = 
	-<**/*.cpp>
	+<**/pir-led.cpp>
lib_deps =

[env:ultra-led]
build_src_filter = 
	-<**/*.cpp>
	+<**/ultra-led.cpp>
lib_deps =

[env:read-write-rfid]
build_src_filter = 
	-<**/*.cpp>
	+<**/read-write-rfid.cpp>
lib_deps =

[env:easy-read-rfid]
build_src_filter = 
	-<**/*.cpp>
	+<**/easy-read-rfid.cpp>
lib_deps =

[env:rfid-final]
build_src_filter = 
	-<**/*.cpp>
	+<**/rfid-final.cpp>
lib_deps =

[env:reading-rfid-interruption]
build_src_filter = 
	-<**/*.cpp>
	+<**/reading-rfid-interruption.cpp>
lib_deps =

[env:buzzer]
build_src_filter = 
	-<**/*.cpp>
	+<**/buzzer.cpp>
lib_deps =

[env:mqtt-test]
build_src_filter = 
	-<**/*.cpp>
	+<**/mqtt-test.cpp>
lib_deps =

[env:FINAL]
build_src_filter = 
	-<**/*.cpp>
	+<**/FINAL.cpp>
lib_deps =

[env:Nodo-1]
build_src_filter = 
	-<**/*.cpp>
	+<**/Nodo-1.cpp>
lib_deps =

[env:Nodo-2]
build_src_filter = 
	-<**/*.cpp>
	+<**/Nodo-2.cpp>
lib_deps =

[env:Nodo-3]
build_src_filter = 
	-<**/*.cpp>
	+<**/Nodo-3.cpp>
lib_deps =

[env:rfid_pir]
build_src_filter = 
    -<**/*.cpp>
    +<**/rfid_pir.cpp>
lib_deps =
    mathworks/ThingSpeak@^2.0.0
    MFRC522
    Ticker
    ESP8266WiFi
    SPI